### PR TITLE
Update fsdocs-tool

### PR DESCRIPTION
**Pull request by nojaf**
Hi, I saw this docs website on Twitter this week.
This version of fsdocs-tool has a nicer theme.

### CODE REVIEW

**Comment by krauthaufen** [comment]
looks like some styling is broken here: https://fsprojects.github.io/FSharp.Data.Adaptive/

any ideas how to fix it?

**Comment by nojaf** [comment]
Looks good on my end, can you share some more details on what seem off?

**Comment by krauthaufen** [comment]
Sorry, browser caches messed things up. My bad.

Looks really fancy!

**Comment by nojaf** [comment]
Ah, glad to hear that!

**Pull request merged**
